// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNX4TzuDEL_lPa8YoMe9I08nrnvbPAprw',
    appId: '1:266366762633:web:07aaae01e397c232f75058',
    messagingSenderId: '266366762633',
    projectId: 'lapmart-90c2a',
    authDomain: 'lapmart-90c2a.firebaseapp.com',
    storageBucket: 'lapmart-90c2a.firebasestorage.app',
    measurementId: 'G-32TR15KVBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwvI4MydnZMus2Qlx_ImyNviGLSVJ6MdQ',
    appId: '1:266366762633:android:7b0fc9f0784cac46f75058',
    messagingSenderId: '266366762633',
    projectId: 'lapmart-90c2a',
    storageBucket: 'lapmart-90c2a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCclOtfE_Lm_uBEsByeMm-KzQOY0B727f0',
    appId: '1:266366762633:ios:8631fa246f4b66d4f75058',
    messagingSenderId: '266366762633',
    projectId: 'lapmart-90c2a',
    storageBucket: 'lapmart-90c2a.firebasestorage.app',
    iosBundleId: 'com.example.lapMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCclOtfE_Lm_uBEsByeMm-KzQOY0B727f0',
    appId: '1:266366762633:ios:8631fa246f4b66d4f75058',
    messagingSenderId: '266366762633',
    projectId: 'lapmart-90c2a',
    storageBucket: 'lapmart-90c2a.firebasestorage.app',
    iosBundleId: 'com.example.lapMart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNX4TzuDEL_lPa8YoMe9I08nrnvbPAprw',
    appId: '1:266366762633:web:1e7ae8ffd759a869f75058',
    messagingSenderId: '266366762633',
    projectId: 'lapmart-90c2a',
    authDomain: 'lapmart-90c2a.firebaseapp.com',
    storageBucket: 'lapmart-90c2a.firebasestorage.app',
    measurementId: 'G-LD8GVSV74R',
  );
}
