// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF-hoPG12TuwpKKVyeRVTruut3rkmNiGg',
    appId: '1:592372405243:web:f54fcdd10bc0baf056b15e',
    messagingSenderId: '592372405243',
    projectId: 'labmart-62a0f',
    authDomain: 'labmart-62a0f.firebaseapp.com',
    databaseURL: 'https://labmart-62a0f-default-rtdb.firebaseio.com',
    storageBucket: 'labmart-62a0f.appspot.com',
    measurementId: 'G-CXPCPTGN4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb42HPZRystgZdZBE_cIlMriAGCMsgnxY',
    appId: '1:592372405243:android:084f1c9ac2de16bf56b15e',
    messagingSenderId: '592372405243',
    projectId: 'labmart-62a0f',
    databaseURL: 'https://labmart-62a0f-default-rtdb.firebaseio.com',
    storageBucket: 'labmart-62a0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyqBWedTBYSZjcfEIz3YyLk-H18191blw',
    appId: '1:592372405243:ios:194b0fbaea6b3f7456b15e',
    messagingSenderId: '592372405243',
    projectId: 'labmart-62a0f',
    databaseURL: 'https://labmart-62a0f-default-rtdb.firebaseio.com',
    storageBucket: 'labmart-62a0f.appspot.com',
    iosBundleId: 'com.example.lapMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyqBWedTBYSZjcfEIz3YyLk-H18191blw',
    appId: '1:592372405243:ios:194b0fbaea6b3f7456b15e',
    messagingSenderId: '592372405243',
    projectId: 'labmart-62a0f',
    databaseURL: 'https://labmart-62a0f-default-rtdb.firebaseio.com',
    storageBucket: 'labmart-62a0f.appspot.com',
    iosBundleId: 'com.example.lapMart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF-hoPG12TuwpKKVyeRVTruut3rkmNiGg',
    appId: '1:592372405243:web:906a196dcabb418356b15e',
    messagingSenderId: '592372405243',
    projectId: 'labmart-62a0f',
    authDomain: 'labmart-62a0f.firebaseapp.com',
    databaseURL: 'https://labmart-62a0f-default-rtdb.firebaseio.com',
    storageBucket: 'labmart-62a0f.appspot.com',
    measurementId: 'G-DHMZQVETK5',
  );

}